Repository SwissDataScienceCenter/renku, pull requests merged in 2018-09, with the labels that each got.

#402 New developer setup
  docs/developer/index.rst
  docs/developer/minikube.rst
  docs/developer/setup.rst
Labels: documentation

#413 Add missing helm chart repo
  docs/developer/setup.rst
Labels: documentation

#401 Version pinning to release 0.2.0
  charts/gitlab/values.yaml
Labels: meta

#415 0.2.0 rc4
  charts/gitlab/Chart.yaml
  charts/renku/Chart.yaml
  charts/renku/requirements.lock
  charts/renku/requirements.yaml
  charts/renku/values.yaml
Labels: ci
