Repository SwissDataScienceCenter/renku, pull requests merged in 2018-08, with the labels that each got.

#349 ci: no deploy on cron jobs
  .travis.yml
Labels: ci

#382 Cleanup main repo
  Makefile
  README.rst
  charts/renku/templates/tests/test-renku.yaml
  docker-compose.yml
  docs/developer/minikube.rst
  scripts/renku-start.sh
  scripts/renku-wipe.sh
  scripts/run-tests.sh
  services/cassandra/etc/cassandra-env.sh
  services/gitlab/.dockerignore
  services/gitlab/Auto-DevOps.gitlab-ci.yml
  services/keycloak/Dockerfile
  services/keycloak/docker-entrypoint.sh
  services/keycloak/renku-realm.json.tpl
  services/logging/renku_python_logging.yml
  services/postgres/docker-entrypoint-initdb.d/gitlab_db/00.create_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/gitlab_db/01.init_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/init_gitlab_db.sh
  services/postgres/docker-entrypoint-initdb.d/init_keycloak_db.sh
  services/postgres/docker-entrypoint-initdb.d/init_mutation_db.sh
  services/postgres/docker-entrypoint-initdb.d/init_storage_db.sh
  services/postgres/docker-entrypoint-initdb.d/init_types_db.sh
  services/postgres/docker-entrypoint-initdb.d/keycloak_db/00.create_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/keycloak_db/01.init_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/mutation_db/00.create_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/mutation_db/01.init_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/mutation_db/02.create_tables.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/storage_db/00.create_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/storage_db/01.init_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/types_db/00.create_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/types_db/01.init_db.postgres.sql
  services/postgres/docker-entrypoint-initdb.d/types_db/02.create_tables.postgres.sql
  services/storage/data/.gitkeep
  services/traefik/ssl/test.crt
  services/traefik/ssl/test.key
  tests/Dockerfile
  tests/demo-cleanup.sh
Labels: documentation, enhancement

#391 jh: improve the notebook server setup
  services/jupyterhub/spawners.py
Labels: enhancement

#355 Docs: tutorial for web UI
  docs/_static/images/jupyterlab-data-open-csv.png
  docs/_static/images/jupyterlab-files-notebooks.png
  docs/_static/images/jupyterlab-new-notebook.png
  docs/_static/images/jupyterlab-open-terminal.png
  docs/_static/images/jupyterlab-rename.png
  docs/_static/images/renku-ui-close-ku.png
  docs/_static/images/renku-ui-comment-1.png
  docs/_static/images/renku-ui-embed-notebook.png
  docs/_static/images/renku-ui-kus-list.png
  docs/_static/images/renku-ui-new-ku-comment.png
  docs/_static/images/renku-ui-new-ku.png
  docs/_static/images/ui_create_project.png
  docs/_static/images/ui_star_project.png
  docs/_static/zhbikes/DataPreprocess.ipynb
  docs/_static/zhbikes/Explore.ipynb
  docs/user/firststeps.rst
  docs/user/index.rst
Labels: documentation, help wanted
