Repository SwissDataScienceCenter/renku, pull requests merged in 2020-06, with the labels that each got.

#1192 cancel auto PRs of same repo
  .github/workflows/auto-reqs-update-pr.yml
Labels: automerge, ci

#1202 fix: so the tests waits enough for a project to get created
  tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
  tests/src/test/scala/ch/renku/acceptancetests/tooling/Grammar.scala
  tests/src/test/scala/ch/renku/acceptancetests/workflows/NewProject.scala
Labels: bug

#1209 ci: remove broken steps in PR-teardown
  .github/workflows/pull-request-teardown.yml
Labels: automerge
