Repository SwissDataScienceCenter/renku, pull requests merged in 2020-11, with the labels that each got.

#1650 docs: fix relative path to reqs
  docs/conf.py
Labels: automerge, autoupdate

#1683 chore: push automatic dependency updates to development
  .github/workflows/auto-reqs-update-pr.yml
  .github/workflows/deploy.yml
  actions/update-component-version/update-upstream.sh
Labels: automerge, autoupdate

#1675 docs: refresh first steps tutorial
  docs/_static/images/ui_02_new-project.png
  docs/_static/images/ui_04_connect-to-server.png
  docs/tutorials/first_steps/01_create_project.rst
  docs/tutorials/first_steps/02_add_data.rst
  docs/tutorials/first_steps/06_create_workflow.rst
Labels: QA

#1685 chore(ci): fix development branch references
  .github/workflows/deploy.yml
  actions/update-component-version/update-upstream.sh
Labels: automerge
