Repository SwissDataScienceCenter/renku, pull requests merged in 2020-10, with the labels that each got.

#1555 fix(ci): let deploy-tmp-notebooks.py fail on helm errors
  charts/deploy-tmp-notebooks.py
Labels: automerge

#1569 chore: put back helm-install script
  scripts/install-helm.sh
Labels: automerge

#1567 chore(charts): update values changelog
  charts/values.yaml.changelog.md
Labels: automerge

#1553 feat(ci): always recreate postgres secret for tmp JH deployment
  charts/deploy-tmp-notebooks.py
Labels: automerge

#1560 1542 template in acceptance tests
  acceptance-tests/README.md
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/BatchRemoveProjectSpec.scala
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/ReplShell.scala
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/model/projects.scala
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/tooling/ExistingProjectSpecData.scala
Labels: do-not-merge

#1579 chore: clean default nb values
  charts/deploy-tmp-notebooks.py
  charts/renku/values.yaml
Labels: do-not-merge

#1573 chore(ci): add possibility to auto-update PRs
  .github/workflows/autoupdate.yaml
Labels: automerge, autoupdate

#1583 chore: auto-update dependency update PRs
  .github/pr-labeler.yml
Labels: automerge, autoupdate

#1624 chore(cd): add manual trigger for CD pipeline on any branch
  .github/workflows/deploy.yml
Labels: autoupdate

#1623 chore(cd): move cd deployment to helm 3
  .github/workflows/deploy.yml
Labels: automerge, autoupdate
