Repository SwissDataScienceCenter/renku, pull requests merged in 2021-02, with the labels that each got.

#1516 chore: minimal values script
  charts/example-configurations/make-values.sh
  charts/example-configurations/minimal-values.tmpl
  docs/admin/index.rst
  docs/admin/prerequisites/certificates.rst
  docs/admin/prerequisites/dns.rst
  docs/admin/prerequisites/nginx.rst
  docs/admin/prerequisites/tiller.rst
  docs/admin/privacycookie.rst
  docs/spelling_wordlist.txt
Labels: charts, documentation

#1960 chore: update renku-ui version to 0.11.5
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectsPage.scala
  helm-chart/renku/requirements.yaml
Labels: automerge

#1956 ci: run deploy and test on edit
  .github/workflows/pull-request-test.yml
Labels: automerge, autoupdate

#1958 test: update acceptance tests to comply with ui changes for 1229
  acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/ProjectPage.scala
Labels: do-not-merge

#1968 Update README.md
  acceptance-tests/README.md
Labels: QA
