Repository SwissDataScienceCenter/renku, pull requests merged in 2021-04, with the labels that each got.

#2061 chore: include community templates
  helm-chart/renku/values.yaml
Labels: automerge, autoupdate

#2065 chore: prep 0.7.10
  CHANGELOG.rst
  docs/spelling_wordlist.txt
  helm-chart/renku/Chart.yaml
  helm-chart/renku/values.yaml
Labels: autoupdate

#2017 chore: update documentation on how to upload data and create datasets
  docs/user/data.rst
Labels: automerge, autoupdate

#2014 chore: update docs on migrating project to Renku instructions
  docs/tutorials/02_migrating_to_renku.rst
Labels: automerge, autoupdate

#2064 Support deploy command for specifying components versions
  .github/workflows/pull-request-test.yml
  actions/check-pr-description/action.yaml
  actions/deploy-renku/deploy-dev-renku.py
Labels: autoupdate

#2076 ci: fix renku-ui-server in the deploy action
  actions/deploy-renku/deploy-dev-renku.py
Labels: autoupdate

#2087 chore: update ui and ui-server version to 0.11.11
  helm-chart/renku/requirements.yaml
Labels: automerge, autoupdate

#2089 chore: update renku-notebooks to 0.8.11
  helm-chart/renku/requirements.yaml
Labels: automerge

#2096 feat(chart): add renku-cli client to keycloak
  helm-chart/example-configurations/minimal-values.tmpl
  helm-chart/renku/templates/_keycloak-clients-users.tpl
  helm-chart/renku/values.yaml
  helm-chart/values.yaml.changelog.md
Labels: autoupdate

#2073 chore: add info about the check description action
  README.rst
  actions/check-pr-description/README.md
  docs/conf.py
  docs/developer/contributing/index.rst
  docs/developer/contributing/pull-requests.rst
  docs/gensidebar.py
  docs/spelling_wordlist.txt
Labels: autoupdate
